### ISSUE TITLE
Sensirion SCD30 is listed but does not show on 0.9.7-1b30422

### ISSUE THREAD

**Issue by AMTQ** [fablabbcn/smartcitizen-docs#13]
On https://docs.smartcitizen.me/Components/Auxiliary%20Connector/ the SCD30 from Sensirion is listed as supported sensor, but my board does not show it, Is this something that is only available in the prerelease 0.9.8?

**Comment by oscgonfer** [comment]
Hello,
Yes, ATM this is only available in the master branch, but we haven't released a version yet because we want merge [newGPS](https://github.com/fablabbcn/smartcitizen-kit-21/tree/newGPS) branch.

We are expecting this to be done very soon, but in the meantime, working with SCD30 is only possible by building the firmware of current master.

**Comment by AMTQ** [comment]
No worries, I'll wait. If you say "very soon" I assume you mean months rather than years, so I'll keep on testing when it's released.

**Comment by oscgonfer** [comment]
Great! If you want I can send you a compiled firmware that works with SCD30. You can write us at support@smartcitizen.me

**Comment by oscgonfer** [comment]
Hi, closing this as there is a new release in the firmware that supports it officially:
https://forum.smartcitizen.me/t/new-firmware-release-0-9-8/1610
